### ISSUE TITLE
problem with readlink -f on mac

### ISSUE THREAD

**Issue by hth4** [WGLab/Phen2Gene#28] opened 2021-07-11 12:51 UTC
-f is an illegal option for readlink on macs, therefore the setup script fails. A solution is:

brew install coreutils
greadlink -f ...

Best Holger

**Comment by jimhavrilla** [comment] 2021-07-11 15:30
Could you provide more detail than this? For example when you run `which readlink` what does it tell you? I have installed this on macOS Mojave without issues using the `/usr/bin/readlink` version. 
I have noted that in the past, installing tools from MacPorts, Homebrew, etc can cause a lot of problems for many installations. 

I have not seen this issue occur yet.  Could also be Anaconda related.  Are you using the latest Phen2Gene version?

**Comment by hth4** [comment] 2021-07-26 08:46
The readlink on my MacBook Pro (10.13.6. High Sierra) is installed on
/usr/bin/readlink

I installed conda 4.9.2 and cloned the latest Phen2Gene. With my mac I do only testing and would later switch to linux. It could be a readlink bug in older MacOS versions which is fixed now? 

I found more infos and solutions here: 
https://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac

**Comment by jimhavrilla** [comment] 2021-07-26 14:46
Are you saying that it works now? Still using '/usr/bin/readlink' but for a newer macos?

**Comment by hth4** [comment] 2021-07-26 14:57
No, my readlink is still not working. I just replaced readlink with greadlink.

**Comment by jimhavrilla** [comment] 2021-07-26 15:02
I see, and that fixes it...yes, it sounds like from that stackoverflow link
that perhaps the alias script mac wrote for readlink in older versions may
neglect this -f option. For the record I have Mojave, one version ahead of
yours, and it works without issue for me. Perhaps High Sierra was the last
version with this bug. I will see if I can find some other workaround...

**Comment by jimhavrilla** [comment] 2021-07-26 18:58
Since I cannot reproduce your error, I would like you to paste the full traceback if you can.

**Comment by hth4** [comment] 2021-07-26 20:04
readlink -f <somePath>
produces:
readlink: illegal option -- f
usage: readlink [-n] [file ...]

May I discuss another issue with you? My email is hthiele@uni-koeln.de

**Comment by jimhavrilla** [comment] 2021-07-26 20:06
I think I have a fix. I can create a replacement for readlink in setup.sh
or tell mac users to install greadlink and alias readlink.

If you have another issue you can certainly open a new issue. If it's
something unrelated to bugs we can discuss via email.

**Comment by jimhavrilla** [comment] 2021-07-26 20:45
Hey @hth4 I pushed a fix to master, commit d56e764.  Can you git pull and re-run without using greadlink?  I want to be sure it works for you.  It should use universal unix commands.

**Comment by hth4** [comment] 2021-07-27 08:02
The new setup script works for me!
Thank you!

**Comment by jimhavrilla** [comment] 2021-07-27 08:04
Great, I will now close this issue.  Issue fixed with commit d56e764.

**Closed by jimhavrilla** 2021-07-27 08:04 UTC
